### ISSUE TITLE
wiki-reload should be done using actor

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_threebot#112]
reloading a wiki should be done using an actor.

**Comment by serboctor** [comment]
I moved the reload code under `j.tools.markdowndocs.reload`. I also saw a lot of redundancies and inconsistencies in the way we reference different paths so I refactored the `Docsite` class and the `reload` function. Everything seems to be working fine except the deletion scenario which I am still looking into.
I also added an actor that also reloads the wiki.
All relevant code changes are on development_wikireload branch across all relevant repos.

https://github.com/threefoldtech/jumpscaleX_threebot/tree/development_wikireload
https://github.com/threefoldtech/jumpscaleX_libs/tree/development_wikireload
https://github.com/threefoldtech/jumpscaleX_core/tree/development_wikireload

**Comment by serboctor** [comment]
@despiegk I added an actor to reload the wiki if we want to perform it remotely https://github.com/threefoldtech/jumpscaleX_threebot/pull/145/files but for the `jsx wiki-reload` command, I moved the code under `j.tools.markdowndocs.reload`. Since we're reloading local wikis then we dont really need to do it through an actor. Does that make sense to you? or do you want it done differently?

**Comment by hossnys** [comment]
verified 
```
JSX> j.tools.markdowndocs.reload('examples')               
wiki: examples, file: docs/wikis/examples/docs/_sidebar.md.
Reload Success
JSX>  

```
also
```
JSX> cl.actors.content_wiki.reload('examples') 

```
show that is logs 
![Screenshot from 2019-11-03 13-25-18](https://user-images.githubusercontent.com/26298009/68084352-28a6f000-fe3d-11e9-8f55-b8c3a4406cae.png)

![Screenshot from 2019-11-03 11-34-30](https://user-images.githubusercontent.com/26298009/68084391-73286c80-fe3d-11e9-8774-7b503f6dbf11.png)
