### ISSUE TITLE
Some pages can't be found

### ISSUE THREAD

**Issue by Dinaamagdy** [threefoldtech/jumpscaleX_threebot#15]
## Technology  page 
![image](https://user-images.githubusercontent.com/24386802/64357601-430f4980-d005-11e9-9fe4-52cd62631999.png)

## wiki/foundation#/projects/foundation
![image](https://user-images.githubusercontent.com/24386802/64357772-95e90100-d005-11e9-9313-7d44608e5aaa.png)
source file : https://github.com/threefoldfoundation/info_foundation/blob/development/docs/projects/threefoldfoundation.md

## wiki/foundation#/projects/nbhdigital

**Comment by Dinaamagdy** [comment]
### /wiki/foundation#/projects/openchat

**Comment by abom** [comment]
Please make sure the problem is in our wiki lapis app, docsify, loading...etc, not the content.

* For `Technology page`, we do not load [tech wiki](https://github.com/threefoldtech/info_tftech) by default, @andrewayoub do we need to load it by default?

* For `wiki/foundation#/projects/foundation`, this is a content problem, no document called foundation.md (not as you mentioned threefoldfoundation.md) inside [projects folder](https://github.com/threefoldfoundation/info_foundation/tree/master/docs/projects).

* For `wiki/foundation#/projects/freeflownation`, [this file is empty!](https://github.com/threefoldfoundation/info_foundation/blob/master/docs/projects/freeflownation.md)

* For `wiki/foundation#/projects/harvested` , the file `harvested.md` is not found [here](https://github.com/threefoldfoundation/info_foundation/tree/master/docs/projects).

* For wiki/foundation#/projects/nbhdigital, the file `nbhdigital.md` is not found [here](https://github.com/threefoldfoundation/info_foundation/tree/master/docs/projects).


For now, we load wiki from `master` branch as default, so when checking the content, make sure to check `master` branch.
