### ISSUE TITLE
Server responded with non javascript MIME type of "text/html" on multiple SPA packages

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_threebot#195]
![image](https://user-images.githubusercontent.com/64129/68220920-3d2be980-fff1-11e9-818a-903980878f43.png)

**Comment by abom** [comment]
I tested that in one of our SPA applications, and it turns out the build is broken.
This kind of errors will happen if the file requested is not there, so nginx will delegate this to the frontend  (`index.html`) as ` try_files $uri $uri/ {{obj.path_url}}/index.html;`

SPA template config:

```conf
location {{obj.path_url}} {
    alias   {{obj.path_location}};
    index  {{obj.index}};
    try_files $uri $uri/ {{obj.path_url}}/index.html;
}
```

For alerta it gives this error for `https://172.17.0.2/alerta/client/client.3705ed38.js`, and it turns out the file is not found.

```
➜  html git:(development) ls client/client.3705ed38.js
ls: cannot access 'client/client.3705ed38.js': No such file or directory
```

After doing a re-build, it works.

**Comment by abom** [comment]
Do not know how this file is not there, but maybe merges of many builds across multiple machines did this.

In case of cockpit, this [commit](https://github.com/threefoldtech/jumpscaleX_threebot/commit/8c0730a2a611d3af55c1df3d9c53f51a4f78b58c) for example changes the `path_url` of the package to `/` instad of `/cockpit`, which causes the same issue, as the frontend build has a base url/path of `/cockpit` for production, see https://github.com/threefoldtech/tf_cockpit/blob/master/vue.config.js. After trying a build with `/`, it works.

**Comment by abom** [comment]
Updated the builds of alerta, myjobs and pastebin here https://github.com/threefoldtech/jumpscaleX_threebot/commit/6cf506fd93b56f547f3f7e494b363cda29819619

**Comment by hossnys** [comment]
verified also.
