### ISSUE TITLE
export code from explorer on tfgrid [development_actorsimprovement]

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/jumpscaleX_threebot#275]
see new export code on bcdb
on branch: development_actorsimprovement

```jumpscaleX_core/JumpscaleCore/data/bcdb/BCDB.py:148```

- need to export the data to a dir on our explorer (do not upgrade!), just merge the export functionality in.
- [x] complete export, import functions
- [ ] complete [script](https://github.com/threefoldtech/jumpscaleX_threebot/tree/development_actorsimprovement/ThreeBotPackages/tfgrid/backup_explorer)

- [ ] then on another machine running on this branch finish the import feature, see it works and the data is there.

explorer: explorer.testnet.grid.tf

**Comment by despiegk** [comment]
https://github.com/threefoldtech/jumpscaleX_threebot/tree/development_actorsimprovement/ThreeBotPackages/tfgrid/backup_explorer

**Comment by xmonader** [comment]
current status: we did fixes for import export functions and managed to export/import bcdb namespace successfully

**Comment by serboctor** [comment]
Bugs fixed here https://github.com/threefoldtech/jumpscaleX_core/commit/25444d4f0b36fec9159e0b70dc1e77272989392a and here https://github.com/threefoldtech/jumpscaleX_core/commit/957e33fffb9ee6fc16b8193bf8f4f910fda0e932

**Comment by serboctor** [comment]
backup script fixes here https://github.com/threefoldtech/jumpscaleX_threebot/commit/ba9e2a86f0f97332b1f404b1d5e8b20314c0d229

**Comment by serboctor** [comment]
More fixes here https://github.com/threefoldtech/jumpscaleX_core/commit/d5cff66ff4bc9c3fec113eb20a43e23654631cd0

**Comment by serboctor** [comment]
I modified the restore to use the new namespaces according to the package.toml of each package and use zdb. But still didnt manage to test it. I am getting this error from zdb, which @andrewayoub is also investigating.
![Screenshot from 2019-11-25 17-07-16](https://user-images.githubusercontent.com/6323012/69552108-8cd55380-0fa6-11ea-8bb5-864fe572a4b0.png)

**Comment by serboctor** [comment]
@despiegk this part of this commit breaks importing data from explorer
https://github.com/threefoldtech/jumpscaleX_core/pull/284/commits/f94673744f767a0b9e1c3fd3630170f4247417a2#diff-fe139c4b54d2339e936e7dd043098aaaR456

We have models that have indexed columns (other than name) that don't have values

**Comment by serboctor** [comment]
I commented the code mentioned above, so I can continue with my tests. But had some issues with ids in zdb, the first entry in zdb (after the meta) always started at 18. After lots of debugging, and after having some discussions with maxime, it turns out zdb increments the id internally even if you repeatedly update a specific id. And it seems metda data is reepatedtly updated before we create the first objct, as a result it gets created at 18 instead of 1. I am checking what can be changed to avoid this.

**Comment by despiegk** [comment]
waiting till we have [development_actorsimprovement] stable enough

**Comment by gmachtel** [comment]
Sarah working on a parallel track until completely blocked (will be very soon).

**Comment by serboctor** [comment]
Because of the issue I mentioned in my previous commands, I am trying to add a way to add preedefined meta data during the creation of bcdb so it doesnt keep updating zdb if the metadata is there and increase the index. I did the changes locally, but so far it broke a lot of things and I am still trying to work it out.

**Comment by despiegk** [comment]
christophe is ok to restart the grid deployment

**Comment by serboctor** [comment]
@despiegk ok cool. But let's keep this issue in mind. We'll always have a problem with exporting/importing from zdb like I mentioned above.

**Comment by serboctor** [comment]
I added a gist here with some of the changes I was trying to test for future reference 
https://gist.github.com/serboctor/f1182b2e7c9b9a6a7a45da5dfa8a83e3
