### ISSUE TITLE
j.servers.threebot.local_start_default(explorer_debug=True)

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/jumpscaleX_threebot#286]
![image](https://user-images.githubusercontent.com/6021844/69801663-099b4400-11d8-11ea-975f-b047e4dbbf85.png)

need to make sure works again, with and without explorer debug feature

whats role of webplatform, seems weird?

**Comment by xmonader** [comment]
all cleaned up https://github.com/threefoldtech/jumpscaleX_core/blob/798b0294bdbb3e7f25eb1e56476bb191b1c79323/JumpscaleCore/servers/threebot/ThreeBotServersFactory.py#L68


- packages should be `packages paths`, going with name will require to `walk over the packages` because they get loaded in a different process.
