### ISSUE TITLE
3git output files in the wrong dir

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_threebot#327]
![image](https://user-images.githubusercontent.com/64129/71622187-c3714000-2bdc-11ea-83a8-b1935e8fe122.png)

also using /docsites isn't ok, should be in VAR_DIR/docsites

**Comment by abom** [comment]
Using var directory to store docsites now instead of `/docsites` (https://github.com/threefoldtech/jumpscaleX_core/commit/f4d43401693b2a024d9a20cc272d9509d7ef4e92 and https://github.com/threefoldtech/jumpscaleX_threebot/commit/0047aba7a8deb55f6888751e8887ec2ace43adee).

Also, fixed some macros accordingly, now docsites storage path can be accessed from one place as `j.tools.threegit.docsites_path`, no need to hard-code the path when referenced anywhere now.

**Comment by Pishoy** [comment]
verified 
```
kosmos -p 'j.servers.threebot.local_start_3bot(background=False)'
jsx wiki-load -u https://github.com/threefoldfoundation/info_foundation

ls /sandbox/var/docsites/foundation/
circles  images

```
- jsx version 
```
3BOTDEVEL:3bot:jumpscaleX_core: git log -1
commit b0a78ec2ec9b5a9b5e6800cee232a3ab3448c7ef (HEAD -> development_explorer, origin/development_explorer)
Author: andrewayoub <andrew.a.mikhaeel@gmail.com>
Date:   Thu Jan 2 16:30:59 2020 +0200

    fix nested schema properties get
3BOTDEVEL:3bot:jumpscaleX_core: cd /sandbox/code/github/threefoldtech/jumpscaleX_threebot/
3BOTDEVEL:3bot:jumpscaleX_threebot: git log -1
commit 7ca74d465a3d9f30d4a80021853d5f2febca0455 (HEAD -> development_explorer, origin/development_explorer)
Author: andrewayoub <andrew.a.mikhaeel@gmail.com>
Date:   Thu Jan 2 16:29:03 2020 +0200

    remove interactive flag from explorer stress test, can't use console in non interactive mode
```
