### ISSUE TITLE
easier linking in wikis [unstable]

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_threebot#379]
![image](https://user-images.githubusercontent.com/64129/74589092-00698880-500b-11ea-8782-37242da7b9be.png)

please match with the first matching `suffix` no need for the full url. report if there're more matching files.

**Comment by waleedhammam** [comment]
I tried an implementation it turns out. with every link, we need to do a full text search so it caused the process to be
- very slow
- files pointed to each other and made wrong requests ex: `[readme][Readme.md]` didn't get the correct file also if duplicate paths can cause something like deadlock as they poing to eachother.

**Comment by despiegk** [comment]
its not an issue and can be made quick very easily
contact to know how

**Comment by xmonader** [comment]
fixed in 10.4
