### ISSUE TITLE
reporting package for threebot for TFT

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/jumpscaleX_threebot#43]
## features

- [ ] import full blockchain into BCDB tables (using sqlite indexing)
    - see what is the easiest way how to do this, implement a redis backend for the explorer maybe
- [ ] actors to allow nice queries on the TFT blockchain
- query examples on actor
    - nr tokens per wallet or specified wallet
    - ...
- info in BCDB record
    - [X] actor for transactions
    - [ ] wallet addr
    - [ ] nr tft
    - [ ] subobjects = transactions (date, from to who, amount, description, ...)
    -  ...
- [ ] j.tools.rivine_explorer.iterator, iterate over all items and yield the BCDB records
- [X] define models 

## Blockchain deamon
- [ ] try to add a transaction through redis call from the golang deamon
- [ ] try to add several transactions through redis call from the golang deamon
- [ ] verify transactions have been added
- [ ] setup a good timing between transactions feeding (meaning from deamon to 3bot through the redis call) to avoid problem with chain reorganisation

## steps
- [ ] define all actors
- [ ] blockchain guys learn how to create package
- [X] make sure all required code is in right JS repo's
- [ ] let kristof review
- [ ] use builder to have all blockchain components build : need more info
- [ ] start the components in tmux (startupcmd) : need more info
- [ ] use redis backend to explorer which populates the BCDB: need more info
- [ ] some tests & reporting queries

**Comment by zgorizzo69** [comment]
> @GlenDC I have already implemented and tested the transactions part take a look [here](jumpscaleX_threebot/ThreeBotPackages/threefold/tft_explorer) so that you could call that actor to send transactions in bundle and try the flow
> either you could call the actor through a REDIS call
> 
> ```
> cl = j.clients.redis.get(port=8901)
> payload = {"from_addr": "0xmkjxlhxzledhzkjhdzekhdze", "to_addr": "54d65dez46ez4de564d6z4de3dz", "amount": 3}
> encoded_payload = j.data.serializers.json.dumps(payload)
> encoded_response = cl.execute_command("default.tft_explorer.data_dump_transaction", encoded_payload)
> data_dec = j.data.serializers.jsxdata.loads(encoded_response)
> ```
> 
> or you can use the GEDIS endpoint inside nginx
> that only expose 1 endpoint with post method
> there's backend docs on root README.md and there's frontend specific docs on frontend dir/README.md
> https://github.com/threefoldtech/jumpscaleX_core/tree/development/JumpscaleCore/servers/gedis_http
> 
> https://github.com/threefoldtech/jumpscaleX_threebot/blob/development/ThreeBotPackages/myjobs/README.md
> https://github.com/threefoldtech/jumpscaleX_threebot/blob/development/ThreeBotPackages/alerta/README.md
> https://github.com/threefoldtech/jumpscaleX_threebot/blob/development/ThreeBotPackages/pastebin/README.md
> 
> these are the frontend docs
> https://github.com/threefoldtech/jumpscaleX_threebot/blob/development/ThreeBotPackages/pastebin/pastebin/README.md
> https://github.com/threefoldtech/jumpscaleX_threebot/blob/development/ThreeBotPackages/myjobs/JobsVisualSvelte/README.md
> https://github.com/threefoldtech/jumpscaleX_threebot/blob/development/ThreeBotPackages/alerta/alerta/README.md
> for more info about that you can join
> Ahmed Thabet @xmonader

The fastest method would be through the redis protocol according to kristof if you find it easier to go through http tell me then i will adapt the package.py

**Comment by GlenDC** [comment]
Blocked by https://github.com/threefoldtech/jumpscaleX_threebot/issues/85.

**Comment by rkhamis** [comment]
should be unblocked now

**Comment by GlenDC** [comment]
Still blocked by #85, even though you did help me get a bit further @rkhamis.

**Comment by GlenDC** [comment]
Blocked by some issue in JSX. Cannot reach gedis over https. People are on it.

**Comment by GlenDC** [comment]
@xmonader unblocked me. Turned out the documentation linked at <https://github.com/threefoldtech/jumpscaleX_core/blob/development/JumpscaleCore/servers/gedis_http/README.md> was wrong. Will create an issue for it.

I can now succesfully curl to the `tft_explorer` actor:

```
$ curl -k -XGET -H "Content-Type: application/json" https://172.17.0.2/web/gedis/http/tft_explorer/get             
{"error": "Traceback (most recent call last):\n  File \"/sandbox/var/codegen/gedis/main_gedis_threebot/client/default_tft_explorer.py\", line 57, in get\n    res = self._redis.execute_command(cmd_name,data)\n  File \"/usr/local/lib/python3.6/dist-packages/redis/client.py\", line 839, in execute_command\n    return self.parse_response(conn, command_name, **options)\n  File \"/usr/local/lib/python3.6/dist-packages/redis/client.py\", line 853, in parse_response\n    response = connection.read_response()\n  File \"/usr/local/lib/python3.6/dist-packages/redis/connection.py\", line 718, in read_response\n    raise response\nredis.exceptions.ResponseError: {\"traceback\": [[\"/sandbox/lib/jumpscale/Jumpscale/servers/gedis/handlers.py\", \"_handle_request\", 409, \"result = cmd.method(*params_list, user_session=user_session, **params_dict)\", null], [\"/sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/threefold/tft_explorer/actors/tft_explorer.py\", \"get\", 86, \"return self._get_trans(transaction_id)\", null], [\"/sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/threefold/tft_explorer/actors/tft_explorer.py\", \"_get_trans\", 92, \"raise j.exceptions.NotFound(\\\"transaction %s not found\\\" % transaction_id)\", null]], \"message\": \"\\u001b[1;31mEXCEPTION: \\n    transaction 2147483647 not found\\u001b[0;0m\", \"linenr\": 92, \"filepath\": \"/sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/threefold/tft_explorer/actors/tft_explorer.py\", \"processid\": \"unknown\", \"level\": 50, \"context\": \"_get_trans\", \"cat\": null, \"data\": null}\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/sandbox/lib/jumpscale/threebot_packages/zerobot/webinterface/bottle/BottleInterfaceFactory.py\", line 100, in gedis_http\n    result = command(**data[\"args\"])\n  File \"/sandbox/var/codegen/gedis/main_gedis_threebot/client/default_tft_explorer.py\", line 59, in get\n    self.handle_error(e,1,cmd_name=cmd_name)\n  File \"/sandbox/var/codegen/gedis/main_gedis_threebot/client/default_tft_explorer.py\", line 264, in handle_error\n    raise j.exceptions.RemoteException(message=msg, data=logdict, exception=e)\nJumpscale.core.InstallTools.JSExceptions.__init__.<locals>.RemoteException1: None\n"}
```

**Comment by GlenDC** [comment]
Documentation is also updated in the meanwhile.

**Comment by GlenDC** [comment]
Progress:

- Cleaned up and updated the 3Bot package code a bit, also added all the models already that I'll use (all except 1 not used yet, so their structure might still change), from now on progress on in the threebot package code can be followed at: https://github.com/threefoldtech/jumpscaleX_threebot/tree/development_tftexplorer
- Was able to curl GET/POST HTTP calls using the only 2 available set/get methods;
- Did the same thing as in curl, but using Go. This can be found as the following example: <https://github.com/GlenDC/bcdb-go-example>
  - Did it in go so I can get a feel how I'll need to interact with the `TFT Explorer` from Go;
  - Turns out I can simply write and use a small 86L Go client that does all I need (for now) to interact with it, this can be found at https://github.com/GlenDC/bcdb-go-example/blob/f9d976bd1602fe75108f8d761c6789ed88f4cda8/pkg/tftexplorer/client.go#L12-L79
  - Used the _zos_ `schemac` tool (link: <https://github.com/threefoldtech/zos/tree/master/tools/schemac>) to bootstrap my types based on my schemac using the command `pkg/generate.sh ~/sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/threefold/tft_explorer/models tftexplorer`. It's not perfect, but it helped me to quickly bootstrap. Will probably also use this to bootstrap me with all models for the real BCDB-based explorer that I'll add to Rivine.
  - It means that I also make use of the _zos_ `pkg/schema` code found at <https://github.com/threefoldtech/zos/tree/master/pkg/schema> (will add a PR there to support getting a BigInt from a `Numeric` as that is what we'll need for our purposes, and I hope that JSX also uses something that supports big values in python (e.g. `decimal.Decimal`).

Now that my setup works, I know how to develop the actor, know how to use it and know how to interact it from Go code from my host machine, it is time to continue the real work of this task.

Estimated work to be done is about 3 full "dev" days, if all goes according to plan that is. Will as a first step already try to just make sure my chain context is updated based on real data, and take it from there. Goal is to have Friday something to show, and be able to have it finished as a first version to do a full show-and-tell on Monday or Tuesday, next week.

**Comment by GlenDC** [comment]
More progress has been made.

Rivine codebase can now use BCDB as a backend of the Explorer GraphQL instead of StormDB (the default). It is ready for complete syncing. For now as first step I only store the chain context. Tomorrow I'll start storing also the block data and all its child objects. Once that is all working, and the data is reachable from both 3Bot Actor API as well as the GraphQL API, I'll do the wallet support as well. Let's see how fast all this goes.

Quickly tested a new Rivine devnet chain and it seems my data syncs indeed:

```bash
$ bcdb-go-example
{
         "consensus_change_id": "89f53c1bd9df5168aea90859478033455d13abe52a51786c86464268d1feebf6",
         "height": 4,
         "timestamp": 1574208000,
         "block_id": "ab46b2b91acab6fed8ef6c1c0e2cb1be58d9c92d43e71ca50b538ff20e486002"
}
$ bcdb-go-example
{
         "consensus_change_id": "4c8cec31376a21ca276832e06da0aedd59d49eb19dac55f6a90e105ade6f60b4",
         "height": 5,
         "timestamp": 1574208000,
         "block_id": "3474b62e888c95cf4134772cc195f4570ff21126b0293ba1b7c0ba7df0a20606"
}
```

I do notice that there is something weird going on with timestamps. They do not seem to be correctly stored...

Is there something I should know about Date values in schemas @rkhamis? For now I am storing them as integers (UNIX Epoch Timestamp, seconds), is this ok? As it seems that my values are somehow fixed towards specific values, in this example `1574208000`, even though the real values are `1574284481` and `1574284489` respectively.

**Comment by rkhamis** [comment]
@GlenDC : the date type docs are here: https://github.com/threefoldtech/jumpscaleX_core/blob/development/docs/types/date_time.md

let me know if something is unclear
