### ISSUE TITLE
chatflow restarts when you download file instead of going next

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_threebot#459]
for all of the solutions chatflows showing download for wg configs, if you press download and download the file the chat restarts instead of going to next step

**Comment by BolaNasr** [comment]
FIXED

**Comment by hossnys** [comment]
verified on branch unstable :
![Screenshot from 2020-03-23 16-32-34](https://user-images.githubusercontent.com/26298009/77327291-b4091b00-6d23-11ea-949f-3a9559e97928.png)

there was and error in wire-guard config file name when you download it the name contains two dots which is not acceptable as config file name for wireguard, fixed by Bola also .
