### ISSUE TITLE
package stop/delete package location and reload nginx

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_threebot#504]
- go to codeserver tab in admin
- install package
- access codeserver UI
- go to package manager 
- stop codeserver
- go to codeserver tab again

# expected
see install screen for codeserver
# what happens
- bad gateway

**Comment by abom** [comment]
The check for a package status in external view is wrong, it need to be fixed.

To do so, i think we can add an actor to get certain package objects (required packages to be installed), then check their status directly instead of querying all packages like we do here:

https://github.com/threefoldtech/jumpscaleX_threebot/blob/294a2c70f47e428d702574c74873c3e3e7d7b66d/ThreeBotPackages/zerobot/admin/frontend_src/sources/views/external/index.js#L87-L110.


For the actual cleanup/stopping and reloading nginx conf, i think this cannot be done from our side, as every package maintainer defines his own website/locations configuration, also bottle servers or other services, so it needs to be implemented by package maintainers as `stop`, `uninstall` methods.

**Comment by abom** [comment]
Fixed loading packages at https://github.com/threefoldtech/jumpscaleX_core/commit/8ecc64145c5518d638ff4be3a77375b42ad40db0, also fixed checking for package status for external views at this commit: https://github.com/threefoldtech/jumpscaleX_threebot/commit/acc960fcbac06cd77f8888d25ebfa32e9f8ddcff, also it fixed start/stop of `codeserver` package itself too.

**Comment by john-kheir** [comment]
Can't install codeserver package .. not directly part of the issue but need to be handled  
![codeserver_error](https://user-images.githubusercontent.com/15011431/78011992-a3b8f780-7344-11ea-9847-cc36285c1e4b.png)

**Comment by john-kheir** [comment]
was a problem with my docker .. Verified
