### ISSUE TITLE
admin dashboard memory usage is misleading

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_threebot#513]
Please update the memory usage shown in the dashboard to the correct units and which kind of memory

**Comment by RafyAmgadBenjamin** [comment]
### Fixed
updated dashboard to use (res) memory instead of (vms) 
* rss: aka “Resident Set Size”, this is the non-swapped physical memory a process has used. On UNIX it matches “top“‘s RES column). On Windows this is an alias for wset field and it matches “Mem Usage” column of taskmgr.exe.
* vms: aka “Virtual Memory Size”, this is the total amount of virtual memory used by the process. On UNIX it matches “top“‘s VIRT column. On Windows this is an alias for pagefile field and it matches “Mem Usage” “VM Size” column of taskmgr.exe.
### commit
https://github.com/threefoldtech/jumpscaleX_threebot/commit/6b3bfb73c3b9053b82fcbc3116b1e0a858860139


![image](https://user-images.githubusercontent.com/46320202/78267630-78323a80-7507-11ea-9aad-8b10fb614014.png)

![image](https://user-images.githubusercontent.com/46320202/78267644-7bc5c180-7507-11ea-94b2-83d9a1fbe9a2.png)
