### ISSUE TITLE
Reservation of Minio/S3 deploy incl. payment gives error

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/jumpscaleX_threebot#621]
Did standard reservation using chatflow. 

But "error occurred". 

Alerts: 
<img width="473" alt="Schermafbeelding 2020-04-28 om 16 09 06" src="https://user-images.githubusercontent.com/30384423/80497790-344a1e00-896b-11ea-9483-3c0db2145fc8.png">
<img width="473" alt="Schermafbeelding 2020-04-28 om 16 09 58" src="https://user-images.githubusercontent.com/30384423/80497808-39a76880-896b-11ea-8fd9-d15cde357772.png">

**Comment by grimpy** [comment]
Bit of background here:

User was logged in with user "https://explorer.testnet.grid.tf/explorer/users/406"
But his threebot was configured with "https://explorer.testnet.grid.tf/explorer/users/404"

We should always use the configured identity instead of the logged in one, because we do not have access to the privatekey of the logged in user to do any signing

**Comment by rkhamis** [comment]
verified
