### ISSUE TITLE
the total amount taken from my wallet is bigger than the  paid to the farmer with 0.1

### ISSUE THREAD

**Issue by Dina-Abd-Elrahman** [threefoldtech/jumpscaleX_threebot#668]
the total amount taken from my wallet is bigger than the  paid to the farmer with 0.1, this value is transaction fee.

**Comment by gmachtel** [comment]
Normal, no? Part of it goes to the foundation I believe, but @andhartl can you point to the wiki. Maybe also in overview screen where amount to be paid, best to show this split.

**Comment by rkhamis** [comment]
needs to be clear that this is the transaction fee at checkout

**Comment by BolaNasr** [comment]
https://github.com/threefoldtech/jumpscaleX_libs/commit/85cd513d820053b635750bbe8128c1511103cb08

**Comment by gmachtel** [comment]
Beware, it is not only the 0.1 TFT !!! 
I believe also 10% fee goes to the TFFoundation for reserving capacity. Also that aspect needs to be shown. Reason I asked Andreas to comment.

**Comment by zaibon** [comment]
The price sent back to the user already includes the 10% foundation fee. So there is no additional 10%.

**Comment by gmachtel** [comment]
@zaibon I am not talking about the refund. But I thought this issue was about transparently showing to the one reserving capacity in how the amount is split up between farmer, TFF and fee (0.1). 
In a fiat economy, this transparency is a mandatory element on an invoice/receipt. How much goes to seller, how much is VAT. Here we don't have VAT yet but we have the % going to TFF. It's not yet shown to the user, see screenshot. 
![image](https://user-images.githubusercontent.com/30384423/81547833-b0396280-937c-11ea-9f0d-5c31d1974d28.png)

**Comment by zaibon** [comment]
haaa that's what this issue is about. Ok got it. Indeed it would be better to show a full detail of what does where.
The structure returned by the explorer to the client when registering a reservation already contains the detail of how much does to which farmer. @gmachtel maybe write down what you would expect to see he in the summary of the payment so team can change the UI?
