### ISSUE TITLE
Delete 'Create Wallet' button in 3sdk admin panel

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/jumpscaleX_threebot#757]
A user almost lost his tokens as he created a wallet in the admin panel but didn't write down the Stellar secret. He assumed that tokens would appear in 3Bot connect app. 

![image](https://user-images.githubusercontent.com/30384423/84016725-f8e53b00-a97d-11ea-82cb-0b2a3729283b.png)

In next 3Bot connect app, Stellar secret is shown in the wallet, this secret can be used for importing. 
Only keep 'import wallet' and delete 'create wallet' button will 
- eliminate ambiguity about where the secrets are kept
- avoids that people throw away their container and this way loose their Stellar secret
- avoids extra spending of XLMs in uncontrolled way

**Comment by BolaNasr** [comment]
commit: https://github.com/threefoldtech/jumpscaleX_threebot/commit/1b2e0a628cfa15e048921a94fc8a2d6c39d5d862
![image](https://user-images.githubusercontent.com/10259267/84045094-acfbbb80-a9a8-11ea-83ec-2efac50d7ea8.png)

**Comment by zaibon** [comment]
I think the approach to solve the issue encounter by the user is wrong. It seems the issue came from something the user just assume and that was never stated anywhere. It also could have been solved in other ways then simply deleting the feature all-together.

I would like we take a step back on this one and think about our other options.
From the top of my head:
- add a message clearly stating they need to keep their secret safe (like any other crypto wallet, this is just common sense in crypto)
- Explorer the possibility to sync the wallet between the app in the admin panel. At the end, if they share the same seed, so they should be able to generate the same secret.

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
