### ISSUE TITLE
Network reservation not working with FreeTFT on Mainnet

### ISSUE THREAD

**Issue by abdulgig** [threefoldtech/jumpscaleX_threebot#783]
Hi there,

We have a partner who is trying to create a network with "FreeTFT" on Mainnet using the chatflows. He is unable to make a reservation yet and it fails all the time. Another thing we noticed that there is no option given to download the Wireguard config ? The customer waits for the whole 15 minutes and then gets a "Failed Reservation" message.

Couple of his reservations are here, 

[https://explorer.grid.tf/explorer/reservations/10120](https://explorer.grid.tf/explorer/reservations/10120)
[https://explorer.grid.tf/explorer/reservations/10137](https://explorer.grid.tf/explorer/reservations/10137)

These are marked for deletion on the explorer.

Thanks,

![image](https://user-images.githubusercontent.com/25789764/86098853-bf5ca700-bac7-11ea-97a7-6523b780d6b9.png)

**Comment by zaibon** [comment]
The node he uses in not fully started. From the logs I can see it didn't receive an IPV6 address. The node is not processing any reservation at the moment.

**Comment by abdulgig** [comment]
In that case, the chatflows should be able to pick up the most favorable node for a reservation or deployment. The customer is not specifying / choosing any node by himself.

**Comment by zaibon** [comment]
There is a known bug at the moment on mainnet where node that are not fully operational are still reported as online. This is due to the fact that even ipv4 only nodes are eligible for farming. So they MUST be marked as online otherwise they won't get tokens. 
This will be fix in the next version when ipv4 support lands.

In the mean time the best approach is to select farm that are know to be fully up and running.

**Comment by abdulgig** [comment]
Thanks for the explanation 👍. We will ask the user to deploy with that method for now.

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
